source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ScrollableTabs_Example', :exclusive => true do
  pod "ScrollableTabs", :path => "../"
end

target 'ScrollableTabs_Tests', :exclusive => true do
  pod "ScrollableTabs", :path => "../"

  # If you're using Xcode 7 / Swift 2
  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'
end
