source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ScrollableTabs_Example', :exclusive => true do
  pod "ScrollableTabs", :path => "../"
end

target 'ScrollableTabs_Tests', :exclusive => true do
  pod "ScrollableTabs", :path => "../"

#  pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'xcode7.1'
#  pod 'Nimble', '2.0.0-rc.3'
end
